version: "3.3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "node_chat"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "marcus"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"